### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by nicotravassos** [idoko-emmanuel/laravel-fortify-sanctum-auth#1]
Hi @idoko-emmanuel,

Please can you provide a api example for fortify for laravel 11 also include access token if possible alot has changed in laravel 11 think this would be helpful?

**Comment by idoko-emmanuel** [comment]
Alright @nicotravassos I will make it compatible with Laravel 11 after I realese phase 3 of the tutorial

**Comment by nicotravassos** [comment]
Thank you
